---
# tasks file for atb-ansible-zippeddata
- name: create directories for unzipped data
  ansible.builtin.file:
    path: "{{ item.path }}"
    recurse: yes
    state: directory
  with_items: "{{ zippeddata_data }}"

- name: download unzipped data
  ansible.builtin.unarchive:
    src: "{{ item.url }}"
    dest: "{{ item.path }}"
    remote_src: yes
  with_items: "{{ zippeddata_data }}"
